Easy.CMS.Web/Modules/Section/Models/SectionWidget.cs
/* http://www.zkea.net/ Copyright 2016 ZKEASOFT http://www.zkea.net/licenses */
using System;
using System.Collections.Generic;
using Easy.MetaData;
using Easy.Web.CMS.MetaData;
using Easy.Web.CMS.Widget;

namespace Easy.CMS.Section.Models
{
    [DataConfigure(typeof(SectionWidgetMetaData)), Serializable]
    public class SectionWidget : WidgetBase
    {
        public string SectionTitle { get; set; }
        public IEnumerable<SectionGroup> Groups { get; set; }
    }

    class SectionWidgetMetaData : WidgetMetaData<SectionWidget>
    {
        protected override void ViewConfigure()
        {
            base.ViewConfigure();
            ViewConfig(m => m.SectionTitle).AsHidden();
        }
    }
}

Easy.CMS.Web/Modules/Section/Controllers/SectionGroupController.cs
/* http://www.zkea.net/ Copyright 2016 ZKEASOFT http://www.zkea.net/licenses */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Easy.CMS.Section.Models;
using Easy.CMS.Section.Service;
using Easy.Constant;
using Easy.Data;
using Easy.Extend;
using Easy.Web;
using Easy.Web.Attribute;
using Easy.Web.Authorize;
using Easy.Web.CMS.Widget;
using Microsoft.Practices.ServiceLocation;

namespace Easy.CMS.Section.Controllers
{
    [PopUp, DefaultAuthorize]
    public class SectionGroupController : Controller
    {
        private readonly ISectionGroupService _sectionGroupService;
        private readonly ISectionContentProviderService _sectionContentProviderService;
        public SectionGroupController(ISectionGroupService sectionGroupService, ISectionContentProviderService sectionContentProviderService)
        {
            _sectionGroupService = sectionGroupService;
            _sectionContentProviderService = sectionContentProviderService;
        }

        public ActionResult Create(string sectionWidgetId)
        {
            var order = _sectionGroupService.Get("SectionWidgetId", OperatorType.Equal, sectionWidgetId).Count() + 1;
            return View("Form", new SectionGroup
            {
                SectionWidgetId = sectionWidgetId,
                ActionType = ActionType.Create,
                Order = order,
                PartialView = "SectionTemplate.Default",
                GroupName = "组 " + order
            });
        }
        public ActionResult Edit(int Id)
        {
            var group = _sectionGroupService.Get(Id);
            group.ActionType = ActionType.Update;
            return View("Form", group);
        }
        [HttpPost]
        public ActionResult Save(SectionGroup group)
        {
            if (!ModelState.IsValid)
            {
                return View("Form", group);
            }
            if (group.ActionType == ActionType.Create)
            {
                _sectionGroupService.Add(group);
            }
            else
            {
                _sectionGroupService.Update(group);
            }
            ViewBag.Close = true;
            return View("Form", group);
        }

        public JsonResult Delete(int Id)
        {
            _sectionGroupService.Delete(Id);
            return Json(true, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult Sort(List<SectionGroup> groups)
        {
            groups.Each(m =>
            {
                var g = _sectionGroupService.Get(m.ID);
                g.Order = m.Order;
                _sectionGroupService.Update(g);
            });
            return Json(true);
        }

        [HttpPost]
        public JsonResult SortContent(List<SectionContent> contents)
        {
            contents.Each(m =>
            {
                var g = _sectionContentProviderService.Get(m.ID);
                g.Order = m.Order;
                _sectionContentProviderService.Update(g, new DataFilter(new List<string> { "Order" }).Where("ID", OperatorType.Equal, m.ID));
            });
            return Json(true);
        }
        [HttpPost]
        public JsonResult UploadTemplate()
        {
            if (Request.Files.Count > 0)
            {
                try
                {
                    ServiceLocator.Current.GetInstance<IWidgetService>().InstallPackWidget(Request.Files[0].InputStream);
                }
                catch (Exception ex)
                {
                    Logger.Error(ex);
                    return Json(new AjaxResult { Status = AjaxStatus.Error, Message = "上传的模板不正确" });
                }
            }

            return Json(new AjaxResult { Status = AjaxStatus.Normal, Message = "上传成功" });
        }

        [HttpPost]
        public JsonResult SplitColumn(List<SectionGroup> groups)
        {
            if (groups != null)
            {
                groups.Each(g =>
                {
                    if (g.ID > 0)
                    {
                        var group = _sectionGroupService.Get(g.ID);
                        if (group != null)
                        {
                            group.PercentWidth = g.PercentWidth;
                        }
                        _sectionGroupService.Update(group);
                    }
                    else
                    {
                        _sectionGroupService.Add(g);
                    }
                });
            }
            return Json(new { Groups = groups.Count });
        }
    }
}

Easy.CMS.Web/Modules/Section/Controllers/SectionWidgetController.cs
/* http://www.zkea.net/ Copyright 2016 ZKEASOFT http://www.zkea.net/licenses */
using System.Web.Mvc;
using Easy.CMS.Section.Service;
using Easy.Web.Authorize;

namespace Easy.CMS.Section.Controllers
{
    [DefaultAuthorize]
    public class SectionWidgetController : Controller
    {
        private readonly ISectionWidgetService _sectionWidgetService;

        public SectionWidgetController(ISectionWidgetService sectionWidgetService)
        {
            _sectionWidgetService = sectionWidgetService;
        }

        public ActionResult Editor(string sectionWidgetId)
        {
            return View(_sectionWidgetService.Get(sectionWidgetId));
        }


    }
}

Easy.CMS.Web/Modules/Section/Views/SectionTemplate.Default.cshtml
@using Easy.CMS.Section
@using Easy.CMS.Section.Models
@model Easy.CMS.Section.Models.SectionGroup

<div class="section-group-default">
    @foreach (SectionContent content in Model.SectionContents.OrderBy(m => m.Order))
    {
        if (content.SectionContentType == (int)SectionContentBase.Types.CallToAction || content.SectionContentType == (int)SectionContentBase.Types.Image)
        {
            <p>
                @{
            Html.RenderContent(content);
                }
            </p>
        }
        else
        {
            Html.RenderContent(content);
        }
    }
</div>

Easy.CMS.Web/Modules/Section/Views/SectionTemplate.GreyBox.cshtml
@using Easy.CMS.Section
@using Easy.CMS.Section.Models
@model Easy.CMS.Section.Models.SectionGroup

<div class="section-group-grey-box text-center" style="background-color: #f4f4f4; padding: 35px;">
    @foreach (SectionContent content in Model.SectionContents.OrderBy(m => m.Order))
    {
        if (content.SectionContentType == (int)SectionContentBase.Types.CallToAction || content.SectionContentType == (int)SectionContentBase.Types.Image)
        {
            <p>
                @{
            Html.RenderContent(content);
                }
            </p>
        }
        else
        {
            Html.RenderContent(content);
        }
    }
</div>

Easy.CMS.Web/Modules/Section/Views/SectionTemplate.ImageBox.cshtml
@using Easy.CMS.Section.Models
@model Easy.CMS.Section.Models.SectionGroup
@using (Style.AtHead())
{
    <style>
        .image-box-item {
            display: block;
            float: left;
            position: relative;
            margin:1px;
            transition: all .2s linear;
        }
        .image-box-item:hover{
            transform:scale(.98);
        }
        .image-box-item .image-box-description {
            position: absolute;
            bottom: 10px;
            left: 10px;
            right: 10px;
            filter: progid:DXImageTransform.Microsoft.gradient(enabled='true', startColorstr='#CCFFFFFF', endColorstr='#CCFFFFFF');
            background: rgba(255,255,255,.8);
            color: #333;
            text-align: center;
            -webkit-transition: all .35s linear;
            -moz-transition: all .35s linear;
            transition: all .35s linear;
        }
        .image-box-item .image-box-description h3{
            margin:10px;
        }
    </style>
}
<div class="section-group-image-box clearfix">
    @foreach (SectionContentImage content in Model.SectionImages.OrderBy(m => m.Order))
    {

        <a class="image-box-item" href="@Url.PathContent(content.Href)">
            <img src="@Url.PathContent(content.ImageSrc)" alt="@content.ImageAlt" />
            <div class="image-box-description">
                <h3>
                    @content.ImageTitle
                </h3>
                <p>
                    @content.ImageAlt
                </p>
            </div>
        </a>
    }
</div>

Easy.CMS.Web/Modules/Section/Views/SectionTemplate.ImageGreyBox.cshtml
@using Easy.CMS.Section.Models
@model Easy.CMS.Section.Models.SectionGroup
@using (Style.AtHead())
{
    <style>
        .image-grey-box-item {
            display: block;
            float: left;
            position: relative;
            margin:1px;
            transition: all .2s linear;
            text-align: center;
            color: #fff;
        }
        .image-grey-box-item:hover {
            color: #fff;
        }
        .image-grey-box-item .image-box-description {
            position: absolute;
            left: 50%;
            top: 35%;
        }
       .image-grey-box-item .image-box-description-inner {
            position: relative;
            left: -50%;
            border: 1px solid #fff;
       }
        .image-grey-box-item .image-box-description h3{
            margin:10px;
        }
    </style>
}
<div class="section-group-image-box clearfix">
    @foreach (SectionContentImage content in Model.SectionImages.OrderBy(m => m.Order))
    {

        <a class="image-grey-box-item" href="@Url.PathContent(content.Href)">
            <img src="@Url.PathContent(content.ImageSrc)" alt="@content.ImageAlt" />
            <div class="image-box-description">
                <div class="image-box-description-inner">
                    <h3>
                        @content.ImageTitle
                    </h3>
                    <p>
                        @content.ImageAlt
                    </p>
                </div>
            </div>
        </a>
    }
</div>

Easy.CMS.Web/Modules/Section/Views/SectionTemplate.ImageRight.cshtml
@using Easy.CMS.Section
@model Easy.CMS.Section.Models.SectionGroup
<div class="section-group-listView">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-8">
                @{
                    Html.RenderContent(Model.SectionTitle);
                }
                <div class="text-muted">
                    @{
                        Html.RenderContent(Model.Paragraph);
                    }
                </div>
            </div>
            <div class="col-xs-12 col-sm-4">
                @{
                    Html.RenderContent(Model.SectionImage);
                }
            </div>
        </div>
    </div>
</div>

Easy.CMS.Web/Modules/Section/Views/SectionTemplate.JCarousel.cshtml
@using Easy.CMS.Section
@using Easy.CMS.Section.Models
@model Easy.CMS.Section.Models.SectionGroup
@using (Script.AtFoot())
{
    <script type="text/javascript" src="http://cdn.zkeasoft.com/Scripts/jcarousel/jquery.jcarousel.min.js"></script>
    <script type="text/javascript" src="http://cdn.zkeasoft.com/Scripts/jcarousel/jcarousel.basic.js"></script>
}
@using (Style.AtFoot())
{
    <link href="http://cdn.zkeasoft.com/Scripts/jcarousel/jcarousel.basic.css" rel="stylesheet" />
}
<div class="section-group-carousel">
    <div class="jcarousel-wrapper">
        <div class="jcarousel">
            <ul>
                @foreach (SectionContentImage content in Model.SectionImages.OrderBy(m => m.Order))
                {
                    <li>
                        @{
                    Html.RenderContent(content);
                        }
                        
                    </li>
                }
            </ul>
        </div>
        <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
        <a href="#" class="jcarousel-control-next">&rsaquo;</a>
        <p class="jcarousel-pagination">
        </p>
    </div>
</div>

Easy.CMS.Web/Modules/Section/Views/SectionTemplate.LifeStyle.cshtml
@using Easy.CMS.Section
@using Easy.CMS.Section.Models
@model Easy.CMS.Section.Models.SectionGroup
@{
    var images = Model.SectionImages.ToList();
}
@using (Style.AtHead())
{
    <style>
        .life-style-title {
            background: #f7a04c;
            float: left;
            margin: 0;
            width: 100%;
        }

            .life-style-title h3 {
                color: #fff;
                margin-left: 8px;
            }
            .life-style-title h3 a{
                 color: #fff;
                 text-decoration:none;
            }
            .life-style-title .life-style-title-links a {
                float: left;
                text-decoration: none;
                display: block;
                margin: 0 8px 8px 8px;
                padding: 0 15px;
                height: 25px;
                line-height: 25px;
                text-align: center;
                border-radius: 13px;
                background: #ffcfa1;
                color: #7c3d00;
            }
            .life-style-title .life-style-title-links a:hover{
                background: #ffe5cd;
            }
        .life-style-image-box {
            position: relative;
        }
        .life-style-image-box a{
            display:block;
        }
        .life-style-image-box img{
            width:100%;
        }
            .life-style-image-box h3 {
                margin: 10px;
            }

            .life-style-image-box .text {
                position: absolute;
                z-index: 3;
                top: 50%;
                left: 10%;
                margin: -42px 0 0 0;
                padding: 12px 0 10px;
                width: 80%;
                color: #333;
                text-align: center;
                filter: alpha(opacity=0);
                -moz-opacity: 0;
                opacity: 0;
                -webkit-transform: scale(0);
                -moz-transform: scale(0);
                transform: scale(0);
                -webkit-transition: all .35s linear;
                -moz-transition: all .35s linear;
                transition: all .35s linear;
                background: rgba(255, 255, 255, 0.8);
                border: 2px solid #808080;
            }

            .life-style-image-box .mask {
                display: block;
                position: absolute;
                left: 0;
                top: 0;
                width: 100%;
                height: 100%;
                background-color: #000;
                filter: alpha(opacity=0);
                -moz-opacity: 0;
                opacity: 0;
                -webkit-transition: all .35s linear;
                -moz-transition: all .35s linear;
                transition: all .35s linear;
            }

            .life-style-image-box:hover .text {
                filter: alpha(opacity=100);
                -moz-opacity: 1;
                opacity: 1;
                -webkit-transform: scale(1);
                -moz-transform: scale(1);
                transform: scale(1);
            }

            .life-style-image-box:hover .mask {
                filter: alpha(opacity=20);
                -moz-opacity: .2;
                opacity: .2;
            }
    </style>
}
@helper ImageItem(SectionContentImage image)
{
    <div class="life-style-image-box">
        <a href="@Url.PathContent(image.Href)">
            <img src="@Url.PathContent(image.ImageSrc)" alt="@image.ImageAlt" />
            <div class="mask"></div>
            <div class="text">
                <h3>@image.ImageTitle</h3>
                <p>@image.ImageAlt</p>
            </div>
        </a>
    </div>
}
<div class="section-group-life-style">
    <div class="clearfix">
        <div class="col-xs-4">
            <div class="row">
                @if (images.Count > 0)
                {
                    @ImageItem(images[0]);
                }
            </div>
        </div>
        <div class="col-xs-8">
            <div class="row">
                <div class="col-xs-8">
                    <div class="row">
                        @if (images.Count > 1)
                        {
                            @ImageItem(images[1]);
                        }
                    </div>

                </div>
                <div class="col-xs-4">
                    <div class="row">
                        @if (images.Count > 2)
            {
                            @ImageItem(images[2]);
                        }
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <div class="row">
                        @if (images.Count > 3)
            {
                            @ImageItem(images[3]);
                        }
                    </div>
                </div>
                <div class="col-xs-4">
                    <div class="row">
                        @if (images.Count > 4)
            {
                            @ImageItem(images[4]);
                        }
                    </div>
                </div>
                <div class="col-xs-4">
                    <div class="row">
                        @if (images.Count > 5)
            {
                            @ImageItem(images[5]);
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="life-style-title">
        @{
            Html.RenderContent(Model.SectionTitle);
            <div class="clearfix life-style-title-links">
                @foreach (var item in Model.CallToActions)
                {
                    Html.RenderContent(item);
                }
            </div>
        }
    </div>

</div>

Easy.CMS.Web/Modules/Section/Views/SectionTemplate.LinkGroup.cshtml
@using Easy.CMS.Section
@using Easy.CMS.Section.Models
@model Easy.CMS.Section.Models.SectionGroup
<p class="section-group-linkgroup btn-group">
    @foreach (SectionContent content in Model.SectionContents.Where(m => m.SectionContentType == (int)SectionContentBase.Types.CallToAction).OrderBy(m => m.Order))
    {
        SectionContentCallToAction callToAction = content as SectionContentCallToAction;
        if (callToAction != null)
        {
            <a class="btn btn-default" target="@Html.SmartLinkTarget(callToAction.Href)" href="@Url.PathContent(callToAction.Href)">@callToAction.InnerText</a>
        }
    }
</p>
@if (Model.SectionContents.Any(m => m.SectionContentType != (int)SectionContentBase.Types.CallToAction))
{
    <div class="section-group-default">
        @foreach (SectionContent content in Model.SectionContents.Where(m => m.SectionContentType != (int)SectionContentBase.Types.CallToAction).OrderBy(m => m.Order))
        {
            if (content.SectionContentType == (int)SectionContentBase.Types.CallToAction || content.SectionContentType == (int)SectionContentBase.Types.Image)
            {
                <p>
                    @{
                Html.RenderContent(content);
                    }
                </p>
            }
            else
            {
                Html.RenderContent(content);
            }
        }
    </div>

}

Easy.CMS.Web/Modules/Section/Views/SectionTemplate.ListView.cshtml
@using Easy.CMS.Section
@model Easy.CMS.Section.Models.SectionGroup
<div class="section-group-listView">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-4">
                @{
                    Html.RenderContent(Model.SectionImage);
                }
            </div>
            <div class="col-xs-12 col-sm-8">
                @{
                    Html.RenderContent(Model.SectionTitle);
                }
                <div class="text-muted">
                    @{
                        Html.RenderContent(Model.Paragraph);
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Easy.CMS.Web/Modules/Section/Views/SectionTemplate.Quote.cshtml
@using Easy.CMS.Section
@using Easy.CMS.Section.Models
@model Easy.CMS.Section.Models.SectionGroup
<div class="section-group-quote" style="padding:20px">
    <div style="background: url('http://cdn.zkeasoft.com/images/quote-left.png') left top no-repeat;padding-left:40px">
        <div style="background: url('http://cdn.zkeasoft.com/images/quote-right.png') right bottom no-repeat;padding-right:40px">
            @foreach (SectionContent content in Model.SectionContents.OrderBy(m => m.Order))
            {
                if (content.SectionContentType == (int)SectionContentBase.Types.CallToAction || content.SectionContentType == (int)SectionContentBase.Types.Image)
                {
                    <p>
                        @{
                    Html.RenderContent(content);
                        }
                    </p>
                }
                else
                {
                    Html.RenderContent(content);
                }
            }
        </div>
    </div>
</div>

Easy.CMS.Web/Modules/Section/Views/SectionWidgetForm.cshtml
@using Easy.CMS.Section.Models
@model Easy.CMS.Section.Models.SectionWidget
@{
    Script.Reqiured("jQueryUi").AtHead();
    Script.Reqiured("lightBox").AtFoot();
    Script.Reqiured("validate").AtFoot();

    Style.Reqiured("lightBox").AtHead();
    Style.Reqiured("SectionAdmin").AtHead();
    var templates = new List<List<string>>
    {
        new List<string>{""},
        new List<string>{"col-sm-6","col-sm-6"},
        new List<string>{"col-sm-7","col-sm-5"},
        new List<string>{"col-sm-8","col-sm-4"},
        new List<string>{"col-sm-9","col-sm-3"},
        new List<string>{"col-sm-5","col-sm-7"},
        new List<string>{"col-sm-4","col-sm-8"},
        new List<string>{"col-sm-3","col-sm-9"},
        new List<string>{"col-sm-4","col-sm-4","col-sm-4"},
        new List<string>{"col-sm-3","col-sm-6","col-sm-3"},
        new List<string>{"col-sm-3","col-sm-3","col-sm-3","col-sm-3"}
    };

}

@using (Html.BeginForm())
{
    <ul class="nav nav-tabs">
        <li role="presentation"><a href="#info">基本信息</a></li>
        @if (Model.Groups != null)
        {
            <li role="presentation" class="active"><a href="#group">模板分组</a></li>
        }
    </ul>
    <div class="panel panel-default  tab-content">
        <div id="info" class="panel-body tab-pane">
            <input type="hidden" name="ReturnUrl" value="@ViewBag.ReturnUrl" />
            @Html.EditorForModel()
        </div>
        @if (Model.Groups != null)
        {
            <div id="group" class="panel-body tab-pane">

                <div id="section-groups">
                    @foreach (SectionGroup group in Model.Groups.OrderBy(m => m.Order))
                    {
                        Html.RenderPartial("SectionGroup.Edit", group);
                    }
                </div>
                <div class="group-template">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xs-1">
                                <div class="text-center">
                                    <a href="@Url.Action("Create", "SectionGroup", new {sectionWidgetId = Model.ID})" class="btn btn-link btn-xs dialog" data-width="1000" data-height="600">
                                        <i class="glyphicon glyphicon-plus"></i>
                                        添加
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-1">
                                <div class="text-center">
                                    组分列
                                </div>
                            </div>
                            @foreach (var template in templates)
                            {
                                <div class="col-xs-1 item @(template.Count == 1 || !Model.Groups.Any() || template.Count == Model.Groups.Count() ? "" : "hide")">
                                    <div class="row border">
                                        @foreach (var col in template)
                                        {
                                            <div class="col @col" data-col="@col">
                                                <div class="content-helper"></div>
                                            </div>
                                        }
                                    </div>
                                </div>
                            }
                        </div>
                    </div>

                </div>

            </div>
        }
        <div class="panel-footer">
            @if (Model.ID.IsNullOrEmpty())
            {
                <input id="design" type="submit" class="btn btn-primary" value="继续" data-value="@ActionType.Continue" />
            }
            else
            {
                <input id="design" type="submit" class="btn btn-primary" value="保存" data-value="@ActionType.Update"/>
                if (Model.IsTemplate && Model.Thumbnail.IsNotNullAndWhiteSpace())
                {
                    <a href="@Url.Action("Pack", new {Model.ID})" class="btn btn-success">
                        <i class="glyphicon glyphicon-save-file"></i>
                        打包模板
                    </a>
                }
            }
            <input id="copy-widget" type="button" class="btn btn-warning" data-id="@Model.ID" value="复制" />
            <input type="button" class="btn btn-default cancel" value="取消" />
        </div>

    </div>

}
@using (Script.AtFoot())
{
    <script type="text/javascript">
        $(document).on("click", "a.dialog", function () {
            var width = $(this).data("width");
            var height = $(this).data("height");

            Easy.ShowUrlWindow({
                url: $(this).attr("href"), title: $(this).attr("title") || $(this).text(), callBack: function () {
                    reload();
                }, isDialog: true, width: width || 800, height: height || 460
            });
            return false;
        }).on("click", "a.ajax.delete", function () {
            var link = $(this).attr("href");
            Easy.ShowMessageBox("提示", "确定要删除吗？", function () {
                $.get(link, {}, function (data) {
                    reload();
                }, "json");
            }, true, 3);
            return false;
        }).on("click", "#copy-widget", function () {
            $.post("@Url.Action("Copy","Widget",new{module="admin"})", { widgetId: $(this).data("id") }, function (data) {
                Easy.MessageTip.Show(data.Message);
            });
        });
        function reload() {
            $.get("@Url.Action("Editor","SectionWidget")", { sectionWidgetId: '@Model.ID' }, function (html) {
                $("#section-groups").html(html);
                sortGroup();
            }, "html");
        }
        function sortGroup() {
            $("#section-groups").sortable({
                handle: ".sort-handle",
                stop: function (event, ui) {
                    var result = {}
                    $(event.target).find(".section-group").each(function (i) {
                        result["[" + i + "].ID"] = $(this).data("id");
                        result["[" + i + "].Order"] = i + 1;
                    });
                    $.post("@Url.Action("Sort","SectionGroup")", result, function (data) { reload(); }, "json");
                }
            });
            $(".section-group .list-group").sortable({
                handle: ".sort-handle",
                stop: function (event, ui) {
                    var result = {}
                    $(event.target).find(".list-group-item").each(function (i) {
                        result["[" + i + "].ID"] = $(this).data("id");
                        result["[" + i + "].Order"] = i + 1;
                    });
                    $.post("@Url.Action("SortContent","SectionGroup")", result, function (data) { reload(); }, "json");
                }
            });
            var groups = $(".section-group");
            var templateItem = $(".group-template .item");
            $(".actived", templateItem).removeClass("actived");
            templateItem.each(function () {
                var allMatch = true;
                var cols = $(".col", this);
                cols.each(function (i) {
                    if ($(".section-group:eq(" + i + ")").data("col") !== $(this).data("col")) {
                        allMatch = false;
                    }
                });
                if (allMatch && groups.size() === cols.size()) {
                    $(".row", this).addClass("actived");
                }
                if (groups.size() === 0 || cols.size() === 1 || groups.size() === cols.size()) {
                    $(this).removeClass("hide");
                } else {
                    $(this).addClass("hide");
                }
            });
            if ($(".actived", templateItem).size() === 0) {
                var full = true;
                groups.each(function () {
                    if ($(this).data("col")) {
                        full = false;
                    }
                });
                if (full && groups.size() > 0) {
                    templateItem.first().children().addClass("actived");
                }
            }
        }
        $(function () {
            sortGroup();
        });
        $(document).on("click", ".group-template .row.border", function () {
            $(".group-template .row.border").removeClass("actived");
            $(this).addClass("actived");
            var groups = [];
            $(".col", this).each(function (i) {
                groups[i] = {};
                groups[i].PercentWidth = $(this).data("col");
                groups[i].SectionWidgetId = '@Model.ID';
                groups[i].GroupName = "组" + (i + 1);
                groups[i].PartialView = "SectionTemplate.Default";
                groups[i].Order = (i + 1);
                groups[i].ID = $(".section-group:eq(" + i + ")").data("id") || 0;
            });
            var sGroup = $(".section-group");
            if (groups.length !== sGroup.size() && sGroup.size() > 0) {
                groups = [];
                sGroup.each(function (i) {
                    groups[i] = {};
                    groups[i].ID = $(this).data("id");
                    groups[i].PercentWidth = "";
                });
            }
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: "@Url.Action("SplitColumn","SectionGroup",new{module="admin"})",
                data: JSON.stringify(groups),
                contentType: 'application/json; charset=utf-8',
                async: false,
                success: function (data) {
                    if (data.Groups) {

                        reload();
                    }
                }
            });
        });
    </script>
}